version: '3'

services:
  minecraft:
    stdin_open: true
    tty: true
    image: dummyc0m/minecraft
    ports:
      - "25565:25565"
    environment:
      - JAVA_OPTS=-d64 -server -Xmx1024M -Xms1024M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
      - VERSION=1.12.2
    volumes:
      - ./volumes/data:/data
